status:
    project:                 # measuring the overall project coverage
      default:               # context, you can create multiple ones with custom titles
        enabled: yes         # must be yes|true to enable this status
        target: 50%
        threshold: 20%        # allowed to drop X% and still result in a "success" PR status
      branches:
        threshold: 20%        # allowed to drop X% and still result in a "success" commit status
